version: "3.8"

services:
  redis:
    image: "redis:latest"
    container_name: redis
    ports:
      - "6379:6379"

  backend:
    build:
      context: ./todo_app-backend
    ports:
      - "8000:8000"
    volumes:
      - ./todo_app-backend:/app
    depends_on:
      - redis

  frontend:
    build:
      context: ./todo-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
